# This file was generated by GoReleaser. DO NOT EDIT.
class Hellohomebrew < Formula
  desc "BEW 2.5 - Homebrew Hello World"
  homepage "https://github.com/omarsagoo/homebrew-hellohomebrew"
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/omarsagoo/hellohomebrew/releases/download/v1.0.1/hellohomebrew_1.0.1_macOS-64bit.tar.gz"
    sha256 "9f670ece2358afaaea904e66000332eca749308afb9ff42f2f3557e54768ccb2"
  elsif OS.linux?
  end

  def install
    bin.install "hellohomebrew"
  end
end
